#!/usr/bin/bash
while read oldrev newrev refname; do
  echo "Old revision: $oldrev"
  echo "New revision: $newrev"
  echo "Reference name: $refname"

  WC=$HOME/ovirt-engine
  rm -rf $WC $PREFIX
  git clone $HOME/ovirt-engine.git $WC
  pushd $WC

  GIT_DIR=".git" git checkout `basename $refname`

  killall java
  rm -rf $PREFIX/share/ovirt-engine/dbscripts/upgrade
  ( $SCRIPTS_DIR/build.sh && $SCRIPTS_DIR/setup.sh && $SCRIPTS_DIR/run.sh ) | tee $HOME/build.log

  popd
done
